contact_links:
  - name: ðŸ“ƒ Documentation Issue
    url: https://github.com/InboxSDK/inboxsdk-docs/issues/new
    about: This issue tracker is not for documentation issues. Please file documentation issues here.
